### ISSUE TITLE
Test error test_incompatible_versions

### ISSUE THREAD

**Issue by Scriptkiddi** [nilp0inter/cpe#47]
the test function test_incompatible_versions fails with following error, which in my opinion is a syntax error
``` 
self.assertRaises(self.c11_2e == self.c22)
 TypeError: assertRaises() arg 1 must be an exception type or tuple of exception types
```

**Comment by nilp0inter** [comment]
Well , I barely remember this code, but I can't see any evident syntax errors there. Could you point to the exact line where you see that?

**Comment by Scriptkiddi** [comment]
nvm i had the wrong checkout, and thanks for the fast replys man :D
