### ISSUE TITLE
Cut new release

### ISSUE THREAD

**Issue by ostefano** [nilp0inter/cpe#58]
Are new releases planned?

Last one was from 2016, and several contributions took place since then.

CC @nilp0inter @galindale

**Comment by creekorful** [comment]
Hi,

It's on my backlog but I haven't had the time to deal with it yet.

Should happen in the weeks to come.

Cheers!

**Comment by ostefano** [comment]
Sounds good! 

I'll open some PRs then :)

**Comment by agners** [comment]
@creekorful gentle reminder :smile: Is there a release still planned?

**Comment by creekorful** [comment]
Hello @agners waiting a bit for #59, let's see if it can make it to the release :) I will take care of this next week.

Cheers

**Comment by creekorful** [comment]
cpe v1.3.0 has been published to both GitHub and PyPi.

Many thanks to everyone involved! 🎉
